'use client';
import '@/globals.css'
// import { ThemeContextProvider } from "@/components/theme-provider"
import { ThemeProvider } from "@/components/theme-provider"
//import { StrictMode } from 'react'
import { adminConfig } from "@/config/site"
import Navbar from './components/blocks/navbar'
import Footer from './components/blocks/footer'
import AdminSidebar from './components/blocks/admin-sidebar'
import ToastProvider from '@/components/toast-provider'
import Toasts from './components/toasts';
import "./admin-styles.scss";

//import GuardianLayout from '@/components/layout/guard-layout'

/*
export const metadata = {
  title: 'Layout - Admin',
  description: 'Generated by create next app',

  //other: {
  //  'rempl:server': 'localhost:8177',
  //  external: true,    
  //}
}
*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" suppressHydrationWarning>
      <script src="https://cdn.jsdelivr.net/npm/react-render-tracker" async></script>    
      <head />
      <body>
      <ThemeProvider
        defaultTheme="dark"
        enableColorScheme
        themes={['light', 'lightish', 'dark', 'tangerine', 'dark-tangerine', 'mint', 'dark-mint']}
      >
        <ToastProvider>
          <div className="page-container relative">
            <Navbar siteInfo={{name: adminConfig.name, mainNav: adminConfig.mainNav}} />
            <div id="main-container" className="h-screen flex flex-row flex-wrap">
              <AdminSidebar sidebarMenu={adminConfig.sidebarMenu} />
              
              <main id="main" className="bg-gray-950 flex-1 p-6">
                {children}
              </main>              
            </div>
            <Footer />            
          </div>
          <Toasts />
        </ToastProvider>
      </ThemeProvider>       
      </body>        
    </html>
  )
}
